export const screenNames = {
  Home: 'Home',
  HomeScreen: 'HomeScreen',
  Categories: 'Categories',
  Analysis: 'Analysis',
  AnalysisScreen: 'AnalysisScreen',
  Transactions: 'Transactions',
  TransactionsScreen: 'TransactionsScreen',
  Profile: 'Profile',
  Tab: 'Tab',
  QuicklyAnalysisScreen: 'QuicklyAnalysis',
  NotificationsScreen: 'NotificationsScreen',
  CommonScreen: 'CommonScreen',
  OnBoardingScreen: 'OnBoardingScreen',
  WelcomeScreen: 'WelcomeScreen',
  LoginScreen: 'LoginScreen',
  SignupScreen: 'SignupScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  SecurityPinScreen: 'SecurityPinScreen',
  NewPasswordScreen: 'NewPasswordScreen',
  FingerprintScreen: 'FingerprintScreen',
};
