export const en = {
  common: {
    currencySymbol: '$',
    percentage: '{{value}}%',
    positiveAmount: '{{amount}}',
    negativeAmount: '-{{amount}}',
    chartHeader: 'income & Expenses',
    expense: 'expense',
    income: 'income',
    myTargets: 'my targets',
    theme: 'Turn on Dark Mode',
    themeChange: 'Theme is changing !',
    next: 'Next',
    welcomeText:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.',
    login: 'Log In',
    signUp: 'Sign Up',
    forgot: 'Forgot Password?',
    welcomeHeader: 'Welcome',
    userName: 'Username or Email',
    password: 'Password',
    emailPlaceholder: 'example@example.com',
    passwordPlaceholder: '● ● ● ● ● ● ● ●',
    fingerprintText: 'Use Fingerprint To Access',
    fingerprintHightlight: 'Fingerprint',
    signupWith: 'or sign up with',
    signupText: "Don't have an account? Sign Up",
    signuoHightlight: 'Sign Up',
    signupHeader: 'Create Account',
    fullName: 'Full Name',
    email: 'Email',
    mobileNumber: 'Mobile Number',
    dateOfBirth: 'Date of Birth',
    confirmPassword: 'Confirm Password',
    mobileNumberPlaceholder: '+ 123 456 789',
    dateOfBirthPlaceholder: 'DD / MM / YYYY',
    privacyPolicy:
      'By continuing, you agree to\nTerms of Use and Privacy Policy.',
    loginText: 'Already have an account? Log In',
    loginHightlight: 'Log In',
    forgotPasswordHeader: 'Forgot Password',
    securityPinHeader: 'Security Pin',
    newPassword: 'New Password',
    resetPassword: 'Reset Password?',
    resetPasswordText:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    emailText: 'Enter email address',
    nextStep: 'Next Step',
    securityPinText: 'Enter security pin',
    accept: 'Accept',
    sendAgain: 'Send Again',
    changePassword: 'Change Password',
    confirmNewPassword: 'Confirm New Password',
    securityFin: 'Security Fingerprint',
    finTitle: 'Use fingerprint to access',
    finText:
      'Lorem ipsum dolor sit amet, consectetur adipiscing\nelit, sed do eiusmod tempor incididunt.',
    touchId: 'Use touch id',
    touchIdText: '¿Or prefer use pin code?',
    addExpense: 'Add Expenses',
    newCat: 'New Category',
    newCatPlaceholder: 'Write...',
    save: 'Save',
    cancel: 'Cancel',
    date: 'Date',
    category: 'Category',
    categories: 'Categories',
    amount: 'Amount',
    expenseTitle: 'Expense Title',
    messagePlaceholder: 'Enter Message',
    datePlaceholder: 'April 30 ,2024',
    categoryPlaceholder: 'Select the category',
    expenseTitleValue: 'Dinner',
    goal: 'Goal',
    amountSaved: 'Amount Saved',
    addSavings: 'Add Savings',
    profileName: 'John Smith',
    datePlaceholder2: '30 /APR/2023',
    calender: 'Calender',
    spends: 'Spends',
  },

  profile: {
    editProfile: 'Edit Profile',
    security: 'Security',
    setting: 'Settings',
    help: 'Help',
    logout: 'Logout',
    editMyProfile: 'Edit My Profile',
    accountSettings: 'account settings',
    phone: 'Phone',
    emailAdd: 'Email Address',
    userName: 'Username',
    pushNoti: 'push notifications',
    dark: 'turn dark theme',
    updatePro: 'Update Profile',
    changePin: 'Chnage Pin',
    tnc: 'Terms and conditions',
    cpin: 'Current Pin',
    npin: 'New Pin',
    conpin: 'Confirm Pin',
    chpin: 'Change Pin',
    johnFin: 'John Fingerprint',
    addFin: 'Add Fingerprint',
    delete: 'Delete',
    accept: 'Accept',
    tntCheck: 'I accept all the terms and conditions',
    tntRead: 'Read the terms and conditions in more detail at',
    tntLink: 'www.finwiseapp.de',
    pinPlaceholder: '● ● ● ●',
    notiSetting: 'Notification Settings',
    passSetting: 'Password Settings',
    accSetting: 'Account Settings',
    delSetting: 'Delete Account',
    genNoti: 'General Notification',
    soundNoti: 'Sound',
    soundCallNoti: 'Sound Call',
    vibrateNoti: 'Vibrate',
    transactionNoti: 'Transaction Update',
    expenseNoti: 'Expense Reminder',
    budgetNoti: 'Budget Notifications',
    lowNoti: 'Low Balance Alerts',
    cpass: 'Current Password',
    npass: 'New Password',
    conpass: 'Confirm New Password',
    deleteSure: 'Are you sure you want to Log Out?',
    deleteSure2:
      'By deleting your account, you agree that you understand the consequences of this action and that you agree to permanently delete your account and all associated data.',
    delpass: 'Please enter your password to confirm deletion of your account.',
    delBtn: 'Yes, Delete account',
    logbtn: 'Yes, End session',
    logTitle: 'End Session',
    helpTitle: 'Help & FAQS',
    helpText: 'How Can We Help You?',
    searchPlaceholder: 'Search',
    cserve: 'Customer Service',
    web: 'Website',
    facebook: 'Facebook',
    whatsapp: 'Whatsapp',
    insta: 'Instagram',
    onlineSup: 'Online Support',
    supTitle: 'support assistant',
    supText: "Hello! I'm here to assist you",
    helpSupTitle: 'help center',
    helpSupText: 'Your account is ready to use',
    ended: 'ended chats',
    anotherChat: 'Start Another Chat',
    chatPlaceholder: 'Write Here...',
  },

  screenHeaders: {
    quicklyAnalysis: 'Quickly Analysis',
    analysis: 'Analysis',
    transactions: 'Transactions',
    profile: 'Profile',
    notifications: 'Notifications',
  },

  greetings: {
    welcomeBack: 'Hi, Welcome Back',
    goodMorning: 'Good Morning',
  },

  balance: {
    totalBalance: 'Total Balance',
    totalExpense: 'Total Expense',
  },

  progress: {
    expenseInsight: '{{value}}% Of Your Expenses, Looks Good.',
  },

  cards: {
    savingsOnGoals: 'Savings\nOn Goals',
    revenueLastWeek: 'Revenue Last Week',
    foodLastWeek: 'Food Last Week',
  },

  filters: {
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
  },

  transactions: {
    salary: 'Salary',
    groceries: 'Groceries',
    rent: 'Rent',

    pantry: 'Pantry',

    recurring: {
      monthly: 'Monthly',
    },
  },

  datetime: {
    timeRange: '{{time}} – {{date}}',
  },

  onBoarding: {
    text1: 'Welcome to\n Expense Manager',
    text2: '¿Are you ready to\n take control of\n your finaces?',
  },
} as const;
